"""add_general_tables

Revision ID: 132e33911b24
Revises: e71fc5d8ba3c
Create Date: 2026-01-24 13:47:32.161666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132e33911b24'
down_revision: Union[str, Sequence[str], None] = 'e71fc5d8ba3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_id'), 'career', ['id'], unique=False)
    op.create_index(op.f('ix_career_title'), 'career', ['title'], unique=False)
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_id'), 'page', ['id'], unique=False)
    op.create_index(op.f('ix_page_slug'), 'page', ['slug'], unique=True)
    op.create_index(op.f('ix_page_title'), 'page', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_title'), table_name='page')
    op.drop_index(op.f('ix_page_slug'), table_name='page')
    op.drop_index(op.f('ix_page_id'), table_name='page')
    op.drop_table('page')
    op.drop_index(op.f('ix_career_title'), table_name='career')
    op.drop_index(op.f('ix_career_id'), table_name='career')
    op.drop_table('career')
    # ### end Alembic commands ###
