"""update_product_foreign_key_constraints

Revision ID: 331705f6780c
Revises: d3b43234b0f2
Create Date: 2026-02-05 12:48:36.847287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331705f6780c'
down_revision: Union[str, Sequence[str], None] = 'd3b43234b0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cartitem_product_id_fkey'), 'cartitem', type_='foreignkey')
    op.create_foreign_key(None, 'cartitem', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orderitem', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('orderitem_product_id_fkey'), 'orderitem', type_='foreignkey')
    op.create_foreign_key(None, 'orderitem', 'product', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('wishlist_product_id_fkey'), 'wishlist', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.create_foreign_key(op.f('wishlist_product_id_fkey'), 'wishlist', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.create_foreign_key(op.f('orderitem_product_id_fkey'), 'orderitem', 'product', ['product_id'], ['id'])
    op.alter_column('orderitem', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'cartitem', type_='foreignkey')
    op.create_foreign_key(op.f('cartitem_product_id_fkey'), 'cartitem', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
